services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/public_html
      - /var/www/public_html/vendor
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:18.4-alpine
    container_name: psgr
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres-data: