name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.4-alpine
        env:
          POSTGRES_DB: analyzer_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d analyzer_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: pdo, pdo_pgsql, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Database Migrations
        run: |
          export PGPASSWORD='password'
          psql -h localhost -U postgres -d analyzer_test -f database.sql

      - name: Run Quality Checks
        run: make check